<?php

/**
 * BaseBlogComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $author
 * @property string $content
 * @property integer $blog_post_id
 * @property BlogPost $BlogPost
 * 
 * @method string      getAuthor()       Returns the current record's "author" value
 * @method string      getContent()      Returns the current record's "content" value
 * @method integer     getBlogPostId()   Returns the current record's "blog_post_id" value
 * @method BlogPost    getBlogPost()     Returns the current record's "BlogPost" value
 * @method BlogComment setAuthor()       Sets the current record's "author" value
 * @method BlogComment setContent()      Sets the current record's "content" value
 * @method BlogComment setBlogPostId()   Sets the current record's "blog_post_id" value
 * @method BlogComment setBlogPost()     Sets the current record's "BlogPost" value
 * 
 * @package    blog
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBlogComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('blog_comment');
        $this->hasColumn('author', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('blog_post_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BlogPost', array(
             'local' => 'blog_post_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}