<?php

/**
 * BlogPostTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BlogPostTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BlogPostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BlogPost');
    }
}