<?php

/**
 * BlogPostTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BlogPostTable extends Doctrine_Table
{
	/**
	 * Returns an instance of this class.
	 *
	 * @return object BlogPostTable
	 */
	public static function getInstance()
	{
		return Doctrine_Core::getTable('BlogPost');
	}

	static public function getLuceneIndex() {
		ProjectConfiguration::registerZend();
		 
		if (file_exists($index = self::getLuceneIndexFile())) {
			return Zend_Search_Lucene::open($index);
		}
		 
		return Zend_Search_Lucene::create($index);
	}

	static public function getLuceneIndexFile() {
		return sfConfig::get('sf_data_dir').'/post.'.sfConfig::get('sf_environment').'.index';
	}

	public function getForLuceneQuery($query) {
		try {
			$index = self::getLuceneIndex();
			
			$hits = $index->find($query);
			
			$pks = array();
			foreach ($hits as $hit)
				$pks[] = $hit->pk;
	
			if (empty($pks))
				return array();
	
			return $this->createQuery('p')
				->whereIn('p.id', $pks)
				->andWhere('p.published = ?', true)
				->limit(50)
				->execute();
		} catch (Zend_Search_Lucene_Exception $e) {
			return array();
		}
	}
	
	public static function generateToken() {
		return md5(uniqid(time()));
	}
}