<?php

/**
 * BlogPostVisitorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BlogPostVisitorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BlogPostVisitorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BlogPostVisitor');
    }
    
    public function cleanup($interval)
    {
    	$time = new DateTime();
    	$time->sub(new DateInterval($interval));
    	
    	$query = $this->createQuery('v')
    		->delete()
    		->where('v.updated_at < ?', $time->format('Y-m-d'));
    	
    	return $query->execute();
    }
}