<?php

/**
 * BlogComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    blog
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BlogComment extends BaseBlogComment
{
	public function save(Doctrine_Connection $conn = null) {
		$ret = parent::save($conn);
		
		$this->getBlogPost()->updateLuceneIndex();
		
		return $ret;
	}
	
	public function __toString() {
		return $this->getContent();
	}
}
