<?php

/**
 * BlogPostVisitorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BlogPostVisitorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BlogPostVisitorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BlogPostVisitor');
    }
}