<?php

/**
 * BlogPost
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    blog
 * @subpackage model
 * @author     Sebastian Herbermann
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BlogPost extends BaseBlogPost
{
	public function getPermaLink()
	{
		return sfContext::getInstance()->getRouting()->generate('post_permalink', $this, true);
	}
	
	public function getExcerpt()
	{
		$lines = explode("\n", $this->getContent());
		$excerpt = "";
		$excertPresent = false;
		foreach ($lines as $line) {			
			$line = trim($line);
			if (!empty($line)) {
				if (!$excertPresent && in_array(str_replace(array('ä', 'ö', 'ü'), 'a', mb_strtolower(mb_substr($line, 0, 1))), range("a", "z"))) {
					$excerpt .= $line."\n";
					$excertPresent = true;
				} elseif (preg_match('/^\[[a-z]+\]: .*$/i', $line) > 0) {
					$excerpt .= $line."\n";
				}
			}
		}
		return $excerpt;
	}
}
