post:
  url:     /
  class:   sfDoctrineRoute
  options: { model: BlogPost, type: list }
  param:   { module: post, action: index, sf_format: html }
  requirements: { sf_method: get }

post_show:
  url:     /:id/:slug
  class:   sfDoctrineRoute
  options: { model: BlogPost, type: object }
  param:   { module: post, action: show, sf_format: html }
  requirements:
    sf_method: get
    id: \d+
  
post_permalink:
  url:     /p/:id
  class:   sfDoctrineRoute
  options: { model: BlogPost, type: object }
  param:   { module: post, action: permalink, sf_format: html }
  requirements: 
    sf_method: get
    id: \d+
  
content_imprint:
  url: /imprint
  param: { module: content, action: imprint, sf_format: html }
  
comment_create:
  url:     /comment
  class:   sfDoctrineRoute
  options: { model: BlogComment, type: object }
  param:   { module: comment, action: create, sf_format: html }
  requirements: { sf_method: post }
  
homepage:
  url: /
  param:   { module: post, action: index, sf_format: html }