post:
  url:     /
  class:   sfDoctrineRoute
  options: { model: BlogPost, type: list }
  param:   { module: post, action: index, sf_format: html }
  requirements: { sf_method: get }
    
post_catchall:
  url:     /:id/*
  class:   sfDoctrineRoute
  options: { model: BlogPost, type: object }
  param:   { module: post, action: catchall, sf_format: html }
  requirements:
    sf_method: get
    id: \d+

post_show:
  url:     /:id/:slug
  class:   sfDoctrineRoute
  options: { model: BlogPost, type: object }
  param:   { module: post, action: show, sf_format: html }
  requirements:
    sf_method: get
    id: \d+

post_permalink:
  url:     /p/:id
  class:   sfDoctrineRoute
  options: { model: BlogPost, type: object }
  param:   { module: post, action: permalink, sf_format: html }
  requirements:
    sf_method: get
    id: \d+
    
post_private:
  url:     /private/:token
  class:   sfDoctrineRoute
  options: { model: BlogPost, type: object }
  param:   { module: post, action: private, sf_format: html }
  requirements:
    sf_method: get
    id: \d+
    
post_search:
  url:    /search
  param:   { module: post, action: search, sf_format: html }

content_imprint:
  url: /imprint
  param: { module: content, action: imprint, sf_format: html }

comment_create:
  url:     /:id/:slug
  class:   sfDoctrineRoute
  options: { model: BlogPost, type: object }
  param:   { module: comment, action: create, sf_format: html }
  requirements: { sf_method: post }

feed:
  url: /feed.rss
  param: { module: post, action: feed, sf_format: rss }

homepage:
  url: /
  param:   { module: post, action: index, sf_format: html }

