all:
  details:
    name: NeatBlog
    contact: Twitster:http://twitter.com/|github:http://github.com/
    imprint: |
      <h2>Imprint</h2>
      <p>Use HTML oder leave blank to let it disappear.</p>
  view:
    language: en # available: en, de
  other:
    tracking: |
      <!-- HTML Tracking code if you wish -->
