all:
  .settings:

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true

    check_lock:             true
    
    standard_helpers: [Partial, I18N]
    
    # I18n
    default_culture: en
    charset: utf-8
    i18n: true