<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('blog_comment', 'blog_comment_blog_post_id_blog_post_id', array(
             'name' => 'blog_comment_blog_post_id_blog_post_id',
             'local' => 'blog_post_id',
             'foreign' => 'id',
             'foreignTable' => 'blog_post',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
    }

    public function down()
    {
        $this->dropForeignKey('blog_comment', 'blog_comment_blog_post_id_blog_post_id');
    }
}