<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('blog_comment', 'author', 'string', '255', array(
             'notnull' => '',
             ));
    }

    public function down()
    {
		$this->changeColumn('blog_comment', 'author', 'string', '255', array(
             'notnull' => '1',
             ));
    }
}