<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version8 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('blog_post_visitor', 'token', 'string', '100', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {

    }
}