<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addblogpost extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('blog_post', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'content' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => NULL,
             ),
             'views' => 
             array(
              'type' => 'integer',
              'default' => 0,
              'length' => 8,
             ),
             'published' => 
             array(
              'type' => 'boolean',
              'default' => 0,
              'length' => 25,
             ),
             'micropost' => 
             array(
              'type' => 'boolean',
              'default' => 0,
              'length' => 25,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             ), array(
             'indexes' => 
             array(
              'blog_post_sluggable' => 
              array(
              'fields' => 
              array(
               0 => 'slug',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('blog_post');
    }
}