<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addblogpostvisitor extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('blog_post_visitor', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'token' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 100,
             ),
             'post' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'views' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'default' => 1,
              'length' => 8,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('blog_post_visitor');
    }
}