<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version8 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('blog_post', 'published_at', 'timestamp', '25', array(
             'notnull' => '1',
             ));
    }
    
    public function postUp() {
        $posts = Doctrine::getTable('BlogPost')
        	->createQuery('p')
        	->execute();
        foreach ($posts as $post) {
        	$post->setPublishedAt($post->getCreatedAt());
        }
        $posts->save();
    	
    }

    public function down()
    {
        $this->removeColumn('blog_post', 'published_at');
    }
}