BlogPost:
  actAs:
    Timestampable: ~
    Sluggable:
      canUpdate: true
  columns:
    title: 
      type: string(255)
      notnull: true
    content:
      type: string
      notnull: true
    markdown:
      type: boolean
      default: true
    views:
      type: integer
      default: 0
    published:
      type: boolean
      default: false
    micropost:
      type: boolean
      default: false
      
BlogComment:  
  actAs:
    Timestampable: ~
  columns:
    author:
      type: string(255)
      notnull: false
    content:
      type: string
      notnull: true
    spam:
      type: boolean
      default: false
    blog_post_id:
      type: integer
      notnull: true
  relations:
    BlogPost:
      onDelete: CASCADE
      foreignAlias: comments
      
BlogPostVisitor:
  actAs:
    Timestampable: ~
  columns:
    token:
      type: string(100)
      notnull: true
    post:
      type: integer
      notnull: true
    views:
      type: integer
      notnull: true
      default: 1