BlogPost:
  actAs:
    Timestampable: ~
    Sluggable:
      canUpdate: true
  columns:
    title: 
      type: string(255)
      notnull: true
    content:
      type: string
      notnull: true
    views:
      type: integer
      default: 0
    published:
      type: boolean
      default: false
    micropost:
      type: boolean
      default: false
      
BlogComment:  
  actAs:
    Timestampable: ~
  columns:
    author:
      type: string(255)
      notnull: true
    content:
      type: string
      notnull: true
    blog_post_id:
      type: integer
      notnull: true
  relations:
    BlogPost:
      onDelete: CASCADE
      foreignAlias: comments